export const data = [
  {
    id: 1,
    firstName: 'David',
    lastName: 'De gea',
    position: 'GK',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 5000000,
    club: 'manchester united',
    popularity: 34,
    points: 500,
    imgClub: '/assets/club/Manchester-United.png',
  },
  {
    id: 2,
    firstName: 'Viktor',
    lastName: 'Tsyhankov',
    position: 'MD',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 15000000,
    club: 'manchester united',
    popularity: 77,
    points: 600,
    imgClub: '/assets/club/Manchester-United.png',
  },
  {
    id: 3,
    firstName: 'Yevhen',
    lastName: 'Banada',
    position: 'DF',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 10400000,
    club: 'dynamo Kyiv',
    popularity: 3,
    points: 178,
    imgClub: '/assets/club/FC_Dynamo_Kyiv_logo.svg',
  },
  {
    id: 4,
    firstName: 'Nika',
    lastName: 'Sichinava',
    position: 'FW',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 8500000,
    club: 'ingolets',
    popularity: 3,
    points: 172,
    imgClub: '/assets/club/ingolets.png',
  },
  {
    id: 5,
    firstName: 'Dmytro',
    lastName: 'Khlobas',
    position: 'FW',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 10000000,
    club: 'desna chernihiv ',
    popularity: 0,
    points: 14,
    imgClub: '/assets/club/330px-FC_Desna.png',
  },
  {
    id: 6,
    firstName: 'Shahab',
    lastName: 'Zahedi',
    position: 'FW',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 8600000,
    club: 'olimpik Donetsk ',
    popularity: 40,
    points: 372,
    imgClub: '/assets/club/300px-FC_Olimpiс_Donetsk.png',
  },
  {
    id: 7,
    firstName: 'Ibrahim',
    lastName: 'Kargbo',
    position: 'FW',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 8000000,
    club: 'olimpik Donetsk ',
    popularity: 0,
    points: 98,
    imgClub: '/assets/club/300px-FC_Olimpiс_Donetsk.png',
  },
  {
    id: 8,
    firstName: 'Artem',
    lastName: 'Kychak',
    position: 'GK',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 2000000,
    club: 'olimpik Donetsk ',
    popularity: 1,
    points: 202,
    imgClub: '/assets/club/300px-FC_Olimpiс_Donetsk.png',
  },
  {
    id: 9,
    firstName: 'Betim',
    lastName: 'Aljimi',
    position: 'GK',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 5000000,
    club: 'olimpik Donetsk ',
    popularity: 0,
    points: 0,
    imgClub: '/assets/club/300px-FC_Olimpiс_Donetsk.png',
  },
  {
    id: 10,
    firstName: 'Andriy',
    lastName: 'Chekotun',
    position: 'GK',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 4000000,
    club: 'olimpik Donetsk ',
    popularity: 0,
    points: 0,
    imgClub: '/assets/club/300px-FC_Olimpiс_Donetsk.png',
  },
  {
    id: 11,
    firstName: 'Talya',
    lastName: 'Mor',
    position: 'GK',
    imgUrl: '/assets/images/Male-Avatar.svg',
    price: 2000000,
    club: 'olimpik Donetsk ',
    popularity: 80,
    points: 990,
    imgClub: '/assets/club/300px-FC_Olimpiс_Donetsk.png',
  },
];
